### ISSUE TITLE
You'll receive a mail when the total file size exceeds 1GB.

### ISSUE THREAD

**Issue by Parth-Vader** [DefCon-007/Committer#1]
Github sends a warning mail when the total file size exceeds 1gb.
Don't know the commits' limit,though.

**Comment by DefCon-007** [comment]
@Parth-Vader : In that case I will just login to server and delete the dotted.txt so that everything can work again :P

**Comment by DefCon-007** [comment]
Also right now size is 1.66KB for around 1700 commits. Accordingly for 1GB there will be around  1,07,38,42,891.

**Comment by Parth-Vader** [comment]
Then lets see what happens :-D
